name: Backend Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install from requirements first
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install testing dependencies separately
        pip install pytest pytest-asyncio pytest-mock httpx freezegun pytest-html

    - name: Run Python tests and Generate Reports
      run: |
        # Add --html flag for HTML report and make it self-contained
        pytest --junitxml=backend-report.xml --html=backend-report.html --self-contained-html tests/
      env:
        OPENAI_API_KEY: "dummy_key_for_tests"
        POSTGRES_HOST: "localhost"
        POSTGRES_PORT: "5333"
        POSTGRES_DB: "testdb"
        POSTGRES_USER: "testuser"
        POSTGRES_PASSWORD: "testpass"
        MOCK_API_BASE_URL: "http://dummy-mock-api.local"

    - name: Upload Backend HTML Test Report
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: backend-html-report-${{ matrix.python-version }}
        path: backend-report.html