# .github/workflows/frontend-ci.yml
name: Frontend React Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Frontend Dependencies
      run: npm ci

    # REMOVED: Install JUnit Reporter step (now in package.json devDependencies)

    - name: Run Frontend Tests and Generate Reports
      # Use environment variables to configure jest-junit output
      # Use the 'test:ci' script defined in package.json
      run: npm run test:ci
      env:
         CI: true
         # Environment variables for jest-junit
         JEST_JUNIT_OUTPUT_DIR: "." # Output in the current dir (frontend/)
         JEST_JUNIT_OUTPUT_NAME: "junit.xml"

    - name: Publish Frontend Test Report Summary
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Frontend Jest Results
        path: frontend/junit.xml # Path relative to repo root
        reporter: jest-junit

    - name: Upload Frontend Coverage Report
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: frontend-coverage-report
        path: frontend/coverage