name: Run Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install from requirements first
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install testing dependencies separately
        pip install pytest pytest-asyncio pytest-mock httpx freezegun pytest-html

    - name: Run tests and Generate Reports
      run: |
        # Add --html flag for HTML report and make it self-contained
        pytest --junitxml=report.xml --html=report.html --self-contained-html tests/
      env:
        OPENAI_API_KEY: "dummy_key_for_tests"
        POSTGRES_HOST: "localhost"
        POSTGRES_PORT: "5333"
        POSTGRES_DB: "testdb"
        POSTGRES_USER: "testuser" # Make sure these match docker-compose for vector store tests
        POSTGRES_PASSWORD: "testpass" # Make sure these match docker-compose
        MOCK_API_BASE_URL: "http://dummy-mock-api.local" # Doesn't need to resolve

    - name: Publish Test Report Summary
      uses: dorny/test-reporter@v1
      if: success() || failure() # Run even if tests fail
      with:
        name: Pytest Results (${{ matrix.python-version }}) # Name of the Check Run
        path: report.xml             # Path to the JUnit XML report
        # FIX: Use the correct reporter value for JUnit XML generated by pytest
        reporter: pytest             # Reporter type
        # Optional: fail-on-error: 'true'

    - name: Upload HTML Test Report
      uses: actions/upload-artifact@v4
      if: success() || failure() # Run even if tests fail
      with:
        name: html-test-report-${{ matrix.python-version }} # Artifact name
        path: report.html # Path to the generated HTML file